### ISSUE TITLE
Suggest to move ImGui::StyleColorsDark(); outside of RenderImGui.cpp

### ISSUE THREAD

**Issue by YangShen398** [vsg-dev/vsgImGui#52]
Hi,

I was using ImGui in vsg for UI. I found that I cannot set my custom ImGui style because the following code. 

[line 137]
(https://github.com/vsg-dev/vsgImGui/blob/e8d161655bc9f095252c1ff97a769f964a2300a7/src/vsgImGui/RenderImGui.cpp#LL137C5-L137C30)

IMO, this line should not be placed here because it overwrites the style which was set previously on the application level. 
For example, I was following the example in vsgimgui_example.cpp to create my own ImGui UI. My default style and other global settings should initialized at this place (which is in my application layer). They only need to be initialized for once and must happen before NewFrame(). But they will be overwritten by this line.

I created one PR for vsgExamples [#223](https://github.com/vsg-dev/vsgExamples/pull/223) and another one for vsgImGui [#52](https://github.com/vsg-dev/vsgImGui/issues/52).

**Comment by robertosfield** [comment]
This looks to be an issue with how ImGui works as a state machine, so ordering can trip up assumptions about what the state might be.

Having state setup in RenderImGui's constructor is probably inappropriate, defaults are probably better.  I'm not the author of that bit of code so I can't answer the original motivation of having the ImGui::SetColorsDask() in the RenderImgGui constructor.  My guess is that it could have been inspired by 3rd party ImGui examples.

 In your own code are you initializing ImGui before RenderImGui is constructed?

Looking at the vsgimgui_example line:

`auto renderImGui = vsgImGui::RenderImGui::create(window, MyGui::create(params, options));
` 
The MyGui will be constructed first, then the RenderImGui will be constructed.  This means any ImGui calls done within the MyGui constructor will be called first, then the RenderImGui constructor & _init() method.  I'm not familiar with ImGui enough to know the etiquette for calling state setting prior to the ImGui::CreateContext() that is done in the RenderImGui::_init().  

While I don't know what behaviour would be intended it strikes me as a area that might cause issues, my assumption would be that one would call ImGUi::CreateConext) before setting any state.

In the vsgimgui_example the way to resolve this would be to add the MyGui::create() to the RenderImGui node after construction.

--

As a general comment, when merging changes I much prefer to only merge changes relevant to topic of the PR rather than have other changes merged in - in the PRs you've sent in there is reformatting of code as well as the changes relevant to the context of the PR, having these extras in the PR makes it harder for me to discern the intent of the changes.

For fixing formatting issues the thing to do is have a PR specifically for that, and keep it separate from other PRs.

**Comment by robertosfield** [comment]
I tried your suggested change to vsgimgui_example and it crashes due to the ImGui::StyleColorsDark() in the MyGui constructor, presumable because it's being called before the RenderImGui constructor/_init() is called.

Do you test this modification to vsgimgui_example?

I can only presume in your own application code you're call ImGui::CreateContext() prior to constructing RenderImGui so avoid this issue.

While I have found that this PR breaks the vsgimgui_example so can't be merged, the suggestion of removing the ImGui::StyleColorsDark() from the RenderImGui::_init() looks sensible. ImGui headers suggest StyleColorsDark() is now the default so should not be required.

I'm closing this PR as it's broken.

**Comment by YangShen398** [comment]
Hi Robert, 

I am sorry about the crash. When I tested, I passed with --font argument which has `ImGui::CreateContext()`;

I guess you can remove `ImGui::StyleColorsDark()` completely as it is not really needed. 

I think a sensible workflow should look like this, using your vsgimgui_example to demonstrate.

```
main.cpp  << entry point
{
... 
auto renderImGui = vsgImGui::RenderImGui::create(window, MyGui::create(params, options)); // my custom gui is constructed.
...
}

MyGui.cpp << my gui implementation detail
{
MyGui(params, options) 
{  
// we set up default settings for ImGui at the constructor
ImGui::CreateContext();
SetupStyle();
SetupColors();

if (params.font) // load the font here 
{

}

}
}

```
Does it make sense? 
Regarding the format issue, I was using clang formatting. I saw there is a .clang-format in the source code. But I do not why the format is different than yours. What am I missing here? In the future, if I want to contribute to the code base, what should I do?

**Comment by robertosfield** [comment]
The suggested modification to avoid the crash confirms my suspicion.  I don't feel that we need to modify the existing example though, it works fine as is, we'd only need you change if we wanted to explicitly set styles in the constructor.  

W.r.t formatting, vsgImGui has clang formatting and it's my intend to use this, but we'll need to avoid reformatting the ImGui headers and source, just reformatting the vsgImGui specific classes.  I haven't done the leg work to avoid this. 

For your submissions just modify the code without reformatting, or run the reformatting first, submit that, then do your mods and submit that, this way we can separate functional changes from non functional ones.  This is important for understanding changes and being able to revert if issues arise.
